# Creating, indexing and slicing and reshaping arrays

### Create and convert data to numpy arrays

In [15]:
import numpy as np

#convert to and create numpy nd(imensional)arrays
data1 = [10, 20, 30]
print(f"data1 is {type(data1)}")
data1 = np.array(data1)
print(f"data1 is now {type(data1)}")

#one dimensional
data2 = np.array([5, 10, 15, 20])
print(f"data2=\n{data2}")
print(f"data2 dimensions: {data2.shape}")

#two dimensional
data3 = np.array([[11,22],
                  [33,44],
                  [55,66]])
print(f"data3=\n{data3}")
print(f"data3 dimensions: {data3.shape}")

data4 = np.array([[[1,2,3], [4,5,6]], 
                  [[1,2,3], [4,5,6]]])
print(f"data4=\n{data4}")
print(f"data4 dimensions: {data4.shape}")

data1 is <class 'list'>
data1 is now <class 'numpy.ndarray'>
data2=
[ 5 10 15 20]
data2 dimensions: (4,)
data3=
[[11 22]
 [33 44]
 [55 66]]
data3 dimensions: (3, 2)
data4=
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
data4 dimensions: (2, 2, 3)


### Indexing arrays

In [20]:
data1 = np.array([11,22,33,44,55])

In [23]:
#indexing one dimensional array
print(f"data1={data1}")
print(f"data1[0]={data[0]}",f"data1[1]={data[1]}")
print(f"data1[-1]={data[-1]}",f"data1[-2]={data[-2]}",f"data1[-5]={data[-5]}")

data1=[11 22 33 44 55]
data1[0]=11 data1[1]=22
data1[-1]=55 data1[-2]=44 data1[-5]=11


In [21]:
data2 = np.array([[11,22],
                 [33,44],
                 [55,66]])

In [26]:
#indexing two dimensional array
print(f"data2=\n{data2}")
#element (0,0)
print(f"data2[0,0]={data2[0,0]}")
#1st row
print(f"1st row of data2[0,]={data2[0,]}")

data2=
[[11 22]
 [33 44]
 [55 66]]
data2[0,0]=11
1st row of data2[0,]=[11 22]


### Slicing arrays

In [69]:
print(f"data1={data1}")
print("")
#access all data in an array
print(f"data1[:]={data1[:]}")
print("")
#positive slicing of a subset of a one-dimensional array
print(f"data1[:1]={data1[:1]}")
print(f"data1[0:1]={data1[0:1]}")
print(f"data1[0:2]={data1[0:2]}")
print(f"data1[2:5]={data1[2:5]}")
print(f"data1[2:]={data1[2:]}")
print("")
#negative slicing of a one-dimensional array
print(f"data1[-1:]={data1[-1:]}")
print(f"data1[-3:]={data1[-3:]}")
print(f"data1[-5:-3]={data1[-5:-3]}")

data1=[11 22 33 44 55]

data1[:]=[11 22 33 44 55]

data1[:1]=[11]
data1[0:1]=[11]
data1[0:2]=[11 22]
data1[2:5]=[33 44 55]
data1[2:]=[33 44 55]

data1[-1:]=[55]
data1[-3:]=[33 44 55]
data1[-5:-3]=[11 22]


### Example slicing two dimensional array

In [73]:
#Split input (X) and variables (y)
data = np.array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
print(f"array=\n{data}")
# separate data
X, y = data[:, :-1], data[:, -1]
print(f"X=\n{X}")
print(f"y=\n{y}")

X, y = (data[:,:2],data[:,2])
print(f"X=\n{X}")
print(f"y=\n{y}")

array=
[[11 22 33]
 [44 55 66]
 [77 88 99]]
X=
[[11 22]
 [44 55]
 [77 88]]
y=
[33 66 99]
X=
[[11 22]
 [44 55]
 [77 88]]
y=
[33 66 99]


In [75]:
# split train and test data
split = 2
train,test = data[:split,:],data[split:,:]
print(f"train data=\n{train}")
print(f"test data=\n{test}")

train data=
[[11 22 33]
 [44 55 66]]
test data=
[[77 88 99]]


### More slicing

In [81]:
data = np.array([
[ 0, 1, 2, 3, 4],
[10,11,12,13,14],
[20,21,21,22,24],
[30,31,32,33,34]])
print(data)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 21 22 24]
 [30 31 32 33 34]]


In [84]:
# items 11,12,21,22
data[1:3,1:3]

array([[11, 12],
       [21, 21]])

In [85]:
#rows 0,2 , all columns
data[[0,2],:]

array([[ 0,  1,  2,  3,  4],
       [20, 21, 21, 22, 24]])

In [87]:
#all rows, columns 2-3
data[:,2:4]

array([[ 2,  3],
       [12, 13],
       [21, 22],
       [32, 33]])

In [89]:
#all rows, columns 2,4 
data[:,[2,4]]

array([[ 2,  4],
       [12, 14],
       [21, 24],
       [32, 34]])

### Array reshaping

In [79]:
data = np.array([[11, 22],
[33, 44],
[55, 66]])
print(f"data=\n{data}")
print(f"data dimensions: {data.shape}")
print(f"Rows: {data.shape[0]}")
print(f"Cols: {data.shape[1]}")

data=
[[11 22]
 [33 44]
 [55 66]]
data dimensions: (3, 2)
Rows: 3
Cols: 2


In [94]:
# reshape 1D array to 2D
data = np.array([11, 22, 33, 44, 55])
print(data)
print("shape",data.shape)

data = data.reshape((data.shape[0], 1))
print(data)
print("shape",data.shape)

[11 22 33 44 55]
shape (5,)
[[11]
 [22]
 [33]
 [44]
 [55]]
shape (5, 1)


In [97]:
# reshape 2D array to 3D
data = np.array([[11, 22],
[33, 44],
[55, 66]])
print(data)
print("dim->",data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data)
print("dim->",data.shape)

[[11 22]
 [33 44]
 [55 66]]
dim-> (3, 2)
[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]
dim-> (3, 2, 1)
