## Slicing arrays

In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
#column 0
a[:,0]

array([1, 5, 9])

In [5]:
#column 1
a[:,1]

array([ 2,  6, 10])

In [6]:
#column 1-2
a[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [28]:
#column 0, 2
a[:,[0,2]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [7]:
#row 1
a[1,:]

array([5, 6, 7, 8])

In [8]:
#row 1-2
a[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Select data with conditions

In [15]:
# column 3
a[:,3]

array([ 4,  8, 12])

In [16]:
#column 3 where condition
a[:,3]>=8

array([False,  True,  True])

In [18]:
#rows where condition in column
a[a[:,3]>=8]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
#rows where condition in column
a[a[:,0] > 3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
a[a[:,0] > 3][:,np.array([True, True, False, True])] #select/filter columns

array([[ 5,  6,  8],
       [ 9, 10, 12]])

## Transpoze data

In [20]:
#transpoze
at = a.T

In [21]:
at

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [35]:
#rows where col 0 = 1 and 4
condition = (a[0,:]==1) + (a[0,:]==4)
print(condition)

[ True False False  True]


In [37]:
at[condition]

array([[ 1,  5,  9],
       [ 4,  8, 12]])

## Cartesian product

In [3]:
#cartesian
x = np.array([1,2,3])
y = np.array([4,5])
np.transpose([np.tile(x, len(y)), np.repeat(y, len(x))])

array([[1, 4],
       [2, 4],
       [3, 4],
       [1, 5],
       [2, 5],
       [3, 5]])